### ISSUE TITLE
Update stated style conventions in §1

### ISSUE THREAD

**Issue by kcopas** [gbif/doc-georeferencing-calculator#1]
The second paragraph of the [intro](https://docs.gbif-uat.org/georeferencing-calculator-manual/1.0/en/#intro) currently outlines conventions:

> Throughout this document there are terms in bold. These signify that there is a very specific meaning for the term as it is being used here, and these are defined in detail in the Glossary of Georeferencing Best Practices, some of which are included in the Glossary of this document as well, for convenience. Terms in italics and not bold (e.g., Input Latitude) are references to fields or their labels in the Calculator. Terms in italics and bold (e.g., georeferenceRemarks) are names of terms in the [Darwin Core].

We're going to make some adjustments here, so I'm flagging this fact in an issue as reminder to update the text.

**Comment by tucotuco** [comment]
Sounds good.
