### ISSUE TITLE
Doubt about Go Here button

### ISSUE THREAD

**Issue by RicardoOrtizG** [gbif/doc-georeferencing-calculator#3]
I don´t understand the use of the button (Go Here/Ir allí), first I think that maybe will show me the point in the map, but looking at the function of the button in the documentation, Is more like a clear and reset function. Maybe the name "Reset" could be more appropriate for this button?. ¿Am I getting it right?

**Comment by tucotuco** [comment]
That's not quite right. The button doesn't clear the calculator of coordinates or reset anything, instead, it captures the coordinates from the results and puts those in the Input coordinate fields. Thus, you could use the "Go To" function to take steps. For example, if you wanted the coordinates of a 10km by 10 km grid cell you could start by entering the input coordinates of the SW corner and 10 km E in a "distance at a heading" calculation, then click on the "Calculate" button. The coordinates of the SE corner would appear in the results. By clicking on the "Go To" button the coordinates of the SE corner would now appear in the Input coordinates fields without having to copy and paste them from the results section. The same process could be used to get the remaining corners of the grid.
